export const LOAD_ONLINE_USERS = 'App/LOAD_ONLINE_USERS';
export const LOAD_ONLINE_USERS_SUCCESS = 'App/LOAD_ONLINE_USERS_SUCCESS';
export const LOAD_ONLINE_USERS_ERROR = 'App/LOAD_ONLINE_USERS_ERROR';
