export const LOAD_USER = 'App/LOAD_USER';
export const LOAD_USER_SUCCESS = 'App/LOAD_USER_SUCCESS';
export const LOAD_USER_ERROR = 'App/LOAD_USER_ERROR';
export const UPDATE_DIMENSIONS = 'App/UPDATE_DIMENSIONS';
export const UPDATE_USER_NAME = 'App/UPDATE_USER_NAME';
